<?php
echo "<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Strict//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd\">\n"; 
echo "<!-- saved from url=(0083)file:///C:/Users/cory.RICEVOELKER/Saved%20Games/UltimateStudyGuides/Test/index.html -->\n"; 
echo "<html xmlns=\"http://www.w3.org/1999/xhtml\"><head><meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n"; 
echo "\n"; 
echo "<title></title>\n"; 
echo "<meta name=\"keywords\" content=\"\">\n"; 
echo "<meta name=\"description\" content=\"\">\n"; 
echo "<link href=\"http://fonts.googleapis.com/css?family=Source+Sans+Pro:200,300,400,600,700,900\" rel=\"stylesheet\">\n"; 
echo "<link href=\"./default.css\" rel=\"stylesheet\" type=\"text/css\" media=\"all\">\n"; 
echo "<link href=\"./fonts.css\" rel=\"stylesheet\" type=\"text/css\" media=\"all\">\n"; 
echo "\n"; 
echo "<!--[if IE 6]><link href=\"default_ie6.css\" rel=\"stylesheet\" type=\"text/css\" /><![endif]-->\n"; 
echo "\n"; 
echo "</head>\n"; 
echo "<body>\n"; 
echo "<div id=\"header-wrapper\">\n"; 
echo "	<div id=\"header\" class=\"container\">\n"; 
echo "		<div id=\"logo\">\n"; 
echo "			<h1><span class=\"fa fa-bolt\"></span><a href=\"./index.html\">Ultimate Study Guides</a></h1>\n"; 
echo "		</div>\n"; 
echo "		<div id=\"menu\">\n"; 
echo "			<ul>\n"; 
echo "				<li><a href=\"./Subjects.html\" accesskey=\"1\" title=\"\">Subjects</a></li>\n"; 
echo "				<li><a href=\"./Upload.html\" accesskey=\"2\" title=\"\">Upload</a></li>\n"; 
echo "				<li class=\"current_page_item\"><a href=\"./MyAccount.html\" accesskey=\"4\" title=\"\">My Account</a></li>\n"; 
echo "				<li><a href=\"./About.html\" accesskey=\"5\" title=\"\">About</a></li>\n"; 
echo "			</ul>\n"; 
echo "		</div>\n"; 
echo "	</div>\n"; 
echo "</div>\n"; 
echo "\n"; 
echo "<div id=\"wrapper\">\n"; 
echo "	<div id=\"featured-wrapper\" style=\"\n"; 
echo "    padding-top: 0;\n"; 
echo "    padding-bottom: 50px;\n"; 
echo "\">\n"; 
echo "		<div id=\"featured\" class=\"extra2 margin-btm container\">\n"; 
echo "			\n"; 
echo "		</div>\n"; 
echo "	</div>\n"; 
echo "</div>\n"; 
echo "<div id=\"copyright\" class=\"container\">\n"; 
echo "	<p>© Untitled. All rights reserved. | Designed by <a href=\"http://templated.co/\" rel=\"nofollow\">TEMPLATED</a>.</p>\n"; 
echo "</div>\n"; 
echo "\n"; 
echo "\n"; 
echo "</body></html>\n";
?>